CREATE TABLE ERP.TBL_FORNECEDOR_ITEM (
 ID NUMBER(8,0) PRIMARY KEY,
 CODIGOITEM VARCHAR2(50) UNIQUE NOT NULL,
 NUMERADORORIGINAL VARCHAR2(50),
 ITEMSIMILAR VARCHAR2(50),
 DESCRICAO VARCHAR2(50),
 VEICULOSAPLICACAO VARCHAR2(50),
 CATEGORIA VARCHAR2(50),
 PERCENTUALDEVENDA VARCHAR2(50),
 UNIDADEMEDIDA VARCHAR2(50),
 PRECOBRUTO NUMBER(10,2),
 NCM VARCHAR2(50),
 IPI VARCHAR2(50),
 ST VARCHAR2(50),
 IMPORTADO VARCHAR2(50),
 CURVADEVENDA VARCHAR2(50),
 PESO VARCHAR2(50),
 ALTURA VARCHAR2(50),
 LARGURA VARCHAR2(50),
 COMPRIMENTO VARCHAR2(50),
 CODIGODEBARRAS VARCHAR2(50),
 COR VARCHAR2(50),
 LADO VARCHAR2(50),
 AMPERAGEM VARCHAR2(50),
 VOLTAGEM VARCHAR2(50),
 POTENCIA VARCHAR2(50),
 SEGMENTO VARCHAR2(50),
 MULTIPLODECOMPRAS VARCHAR2(50),
 QUANTIDADEDEPECAS VARCHAR2(50)
);

CREATE SEQUENCE ERP.SQ_TBL_FORNECEDOR
 START WITH     1
 INCREMENT BY   1
 MAXVALUE 99999999
 NOCACHE
 NOCYCLE;

 CREATE PUBLIC SYNONYM SQ_TBL_FORNECEDOR FOR ERP.SQ_TBL_FORNECEDOR; 